### ISSUE TITLE
BBO-Rietveld running on MacOS 11.4 with Anaconda3 

### ISSUE THREAD

**Issue by kazuki4ito3** [quantumbeam/BBO-Rietveld#2]
Hello, I am using Anaconda for making  up the software development environment;
Anaconda3-2020.11-MacOSX-x86_64.sh
Python 3.8.8 (default, Apr 13 2021, 12:59:45)
gsas2pkg                  2.2.0                         0    briantoby
optuna                    2.8.0              pyhd8ed1ab_0    conda-forge
sqlalchemy                1.4.15           py38h96a0964_0    conda-forge

We have followed the instruction written in this github and run the script 3_LiCoO2.ipynb.
Was there any big change in Optuna between 0.14 and 2.8 ?

Here is the error output  fo Jupyter noteiijjjjjjj
[W 2021-06-14 10:55:07,973] Trial 0 failed because of the following error: AttributeError("Can't pickle local object 'objective.<locals>.evaluate'")
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/optuna/_optimize.py", line 216, in _run_trial
    value_or_values = func(trial)
  File "<ipython-input-5-e13a15789f3e>", line 103, in objective
    p.start()
  File "/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'objective.<locals>.evaluate'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-a18357b7f94c> in <module>
      1 # Optimize
----> 2 study.optimize(objective, n_trials=200, n_jobs=1)

/opt/anaconda3/lib/python3.8/site-packages/optuna/study.py in optimize(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
    399             )
    400 
--> 401         _optimize(
    402             study=self,
    403             func=func,

/opt/anaconda3/lib/python3.8/site-packages/optuna/_optimize.py in _optimize(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
     63     try:
     64         if n_jobs == 1:
---> 65             _optimize_sequential(
     66                 study,
     67                 func,

/opt/anaconda3/lib/python3.8/site-packages/optuna/_optimize.py in _optimize_sequential(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)
    160 
    161         try:
--> 162             trial = _run_trial(study, func, catch)
    163         except Exception:
    164             raise

/opt/anaconda3/lib/python3.8/site-packages/optuna/_optimize.py in _run_trial(study, func, catch)
    265 
    266     if state == TrialState.FAIL and func_err is not None and not isinstance(func_err, catch):
--> 267         raise func_err
    268     return trial
    269 

/opt/anaconda3/lib/python3.8/site-packages/optuna/_optimize.py in _run_trial(study, func, catch)
    214 
    215     try:
--> 216         value_or_values = func(trial)
    217     except exceptions.TrialPruned as e:
    218         # TODO(mamu): Handle multi-objective cases.

<ipython-input-5-e13a15789f3e> in objective(trial)
    101     q = Queue()
    102     p = Process(target=evaluate, args=(trial.number, refine_params_list, q))
--> 103     p.start()
    104     Rwp = q.get()
    105     p.join()

/opt/anaconda3/lib/python3.8/multiprocessing/process.py in start(self)
    119                'daemonic processes are not allowed to have children'
    120         _cleanup()
--> 121         self._popen = self._Popen(self)
    122         self._sentinel = self._popen.sentinel
    123         # Avoid a refcycle if the target function holds an indirect

/opt/anaconda3/lib/python3.8/multiprocessing/context.py in _Popen(process_obj)
    222     @staticmethod
    223     def _Popen(process_obj):
--> 224         return _default_context.get_context().Process._Popen(process_obj)
    225 
    226 class DefaultContext(BaseContext):

/opt/anaconda3/lib/python3.8/multiprocessing/context.py in _Popen(process_obj)
    282         def _Popen(process_obj):
    283             from .popen_spawn_posix import Popen
--> 284             return Popen(process_obj)
    285 
    286     class ForkServerProcess(process.BaseProcess):

/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py in __init__(self, process_obj)
     30     def __init__(self, process_obj):
     31         self._fds = []
---> 32         super().__init__(process_obj)
     33 
     34     def duplicate_for_child(self, fd):

/opt/anaconda3/lib/python3.8/multiprocessing/popen_fork.py in __init__(self, process_obj)
     17         self.returncode = None
     18         self.finalizer = None
---> 19         self._launch(process_obj)
     20 
     21     def duplicate_for_child(self, fd):

/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py in _launch(self, process_obj)
     45         try:
     46             reduction.dump(prep_data, fp)
---> 47             reduction.dump(process_obj, fp)
     48         finally:
     49             set_spawning_popen(None)

/opt/anaconda3/lib/python3.8/multiprocessing/reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

AttributeError: Can't pickle local object 'objective.<locals>.evaluate'

**Comment by resnant** [comment]
Hi @kazuki4ito3,

> Was there any big change in Optuna between 0.14 and 2.8 ?

Yes, it was.
Optuna and GSAS-II are developed very actively, and their backward compatibility is not guaranteed.
This is the reason we provide a Docker container.

Please try to set up our docker container or Optuna 0.14, and make sure you can run `1_Y2O3.ipynb`, which is the simplest case.

If you install Optuna 0.14 into your conda env, this command would work:
```
pip install git+https://github.com/optuna/optuna.git@v0.14.0
```
c.f. https://github.com/quantumbeam/BBO-Rietveld/blob/a6bcb3d94c08289254816b43b96749a4b084f060/docker/Dockerfile#L9

**Comment by resnant** [comment]
I will close this issue. Please reopen this or open another issue if you need discussion.
